precommit: ugprade flake8 to latest v6.1.0
The previous 4.0.1 version of flake8 now hits the following error due to
importlib-metadata >= 5.0.0 removing compatibility shims for deprecated
entry point interfaces:

AttributeError: 'EntryPoints' object has no attribute 'get'

See: https://importlib-metadata.readthedocs.io/en/latest/history.html#v5-0-0

Upgrading to the latest version should get around these issues with
newer importlib-metadata version.